name: 'AWS SDK Go v2 Interface Generator'
description: 'Auto-generate Go interfaces and mocks for AWS SDK Go v2 services using nmccready/aws-sdk-go-v2-ifaces'
branding:
  icon: 'package'
  color: 'orange'

inputs:
  services:
    description: 'Comma-separated list of AWS service names to generate interfaces for (e.g. "s3,dynamodb,sqs"). Leave empty for all services.'
    required: false
    default: ''
  generate-mocks:
    description: 'Also generate mocks using mockery'
    required: false
    default: 'false'
  generate-tests:
    description: 'Also generate tests'
    required: false
    default: 'false'
  output-dir:
    description: 'Directory to copy generated interfaces into (relative to workspace root)'
    required: false
    default: ''
  ifaces-version:
    description: 'Version/ref of nmccready/aws-sdk-go-v2-ifaces to use (tag, branch, or SHA)'
    required: false
    default: 'main'
  commit-results:
    description: 'Commit generated files back to the repo'
    required: false
    default: 'false'
  commit-message:
    description: 'Commit message when commit-results is true'
    required: false
    default: 'chore: update auto-generated AWS SDK Go v2 interfaces'
  create-pr:
    description: 'Create a pull request with generated changes instead of committing directly'
    required: false
    default: 'false'
  pr-title:
    description: 'Pull request title when create-pr is true'
    required: false
    default: 'chore: update auto-generated AWS SDK Go v2 interfaces'
  pr-branch:
    description: 'Branch name for the PR'
    required: false
    default: 'auto-update/aws-ifaces'
  go-version:
    description: 'Go version to use'
    required: false
    default: '1.24'
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '20'

outputs:
  generated-services:
    description: 'List of services that had interfaces generated'
    value: ${{ steps.generate.outputs.services }}
  has-changes:
    description: 'Whether any files were changed'
    value: ${{ steps.check-changes.outputs.has-changes }}

runs:
  using: 'composite'
  steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Clone aws-sdk-go-v2-ifaces
      shell: bash
      run: |
        git clone --depth 1 --branch "${{ inputs.ifaces-version }}" \
          https://github.com/nmccready/aws-sdk-go-v2-ifaces.git \
          "${{ runner.temp }}/aws-sdk-go-v2-ifaces"

    - name: Install dependencies
      shell: bash
      working-directory: ${{ runner.temp }}/aws-sdk-go-v2-ifaces
      run: |
        npm ci --ignore-scripts
        npm run clone_sdk
        ./scripts/install_binary_deps.sh

    - name: Generate interfaces
      id: generate
      shell: bash
      working-directory: ${{ runner.temp }}/aws-sdk-go-v2-ifaces
      run: |
        SERVICES="${{ inputs.services }}"
        SKIP_MOCKS=""
        SKIP_TESTS=""

        if [ "${{ inputs.generate-mocks }}" != "true" ]; then
          SKIP_MOCKS="--skip-mocks"
        fi
        if [ "${{ inputs.generate-tests }}" != "true" ]; then
          SKIP_TESTS="--skip-tests"
        fi

        # Generate interfaces (always)
        ./scripts/gen_ifaces.sh
        go mod tidy -e && go mod vendor

        # Optionally generate mocks
        if [ "${{ inputs.generate-mocks }}" = "true" ]; then
          ./scripts/gen_mocks.sh
          go mod tidy -e && go mod vendor
        fi

        # Optionally generate tests
        if [ "${{ inputs.generate-tests }}" = "true" ]; then
          ./scripts/gen_tests.sh
        fi

        # Filter to requested services if specified
        if [ -n "$SERVICES" ]; then
          echo "Filtering to services: $SERVICES"
          cd service
          for dir in */; do
            svc_name="${dir%/}"
            if ! echo ",$SERVICES," | grep -qi ",$svc_name,"; then
              rm -rf "$svc_name"
            fi
          done
          cd ..
        fi

        # List generated services
        GENERATED=$(ls -d service/*/ 2>/dev/null | xargs -I{} basename {} | tr '\n' ',' | sed 's/,$//')
        echo "services=$GENERATED" >> "$GITHUB_OUTPUT"
        echo "Generated interfaces for: $GENERATED"

    - name: Copy to output directory
      shell: bash
      run: |
        SRC="${{ runner.temp }}/aws-sdk-go-v2-ifaces/service"
        DEST="${{ inputs.output-dir }}"

        if [ -z "$DEST" ]; then
          DEST="${{ github.workspace }}/service"
        else
          DEST="${{ github.workspace }}/$DEST"
        fi

        mkdir -p "$DEST"
        cp -r "$SRC"/* "$DEST"/

        # Also copy go.mod and go.sum if they don't exist in workspace
        IFACES_DIR="${{ runner.temp }}/aws-sdk-go-v2-ifaces"
        if [ ! -f "${{ github.workspace }}/go.mod" ]; then
          cp "$IFACES_DIR/go.mod" "${{ github.workspace }}/"
          [ -f "$IFACES_DIR/go.sum" ] && cp "$IFACES_DIR/go.sum" "${{ github.workspace }}/"
        fi

        echo "Copied generated files to $DEST"

    - name: Check for changes
      id: check-changes
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "has-changes=true" >> "$GITHUB_OUTPUT"
        else
          echo "has-changes=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Commit results
      if: inputs.commit-results == 'true' && steps.check-changes.outputs.has-changes == 'true'
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add -A
        git commit -m "${{ inputs.commit-message }}"
        git push

    - name: Create Pull Request
      if: inputs.create-pr == 'true' && steps.check-changes.outputs.has-changes == 'true'
      shell: bash
      working-directory: ${{ github.workspace }}
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        BRANCH="${{ inputs.pr-branch }}"
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git checkout -b "$BRANCH"
        git add -A
        git commit -m "${{ inputs.commit-message }}"
        git push -u origin "$BRANCH" --force
        
        # Create PR if one doesn't already exist
        EXISTING=$(gh pr list --head "$BRANCH" --json number --jq '.[0].number' 2>/dev/null || true)
        if [ -z "$EXISTING" ]; then
          gh pr create \
            --title "${{ inputs.pr-title }}" \
            --body "Auto-generated AWS SDK Go v2 interfaces update.

        Generated services: ${{ steps.generate.outputs.services }}

        This PR was created automatically by [aws-ifaces-action](https://github.com/brickhouse-tech/aws-ifaces-action)." \
            --head "$BRANCH"
        else
          echo "PR #$EXISTING already exists for branch $BRANCH"
        fi
